### PR TITLE
Fix Catboi's username capitalization

### PR DESCRIPTION
**Pull request by coolcalcacol**

### CODE REVIEW

**Comment by DonovanDMC** [comment]
I'm merging this garbage just to spite @Catboi8

**Comment by DonovanDMC** [comment]
@ErisPRUpdateBot merge

**Comment by coolcalcacol** [comment]
Have a blessed day

**Comment by doomestee** [comment]
My bot has been working phenomenally well until recently when I updated the package.json, I noticed that this commit might have something to do with this. Can I suggest reversing the change please?

**Comment by DonovanDMC** [comment]
This commit changed nothing but the readme

**Comment by JustCat80** [comment]
> My bot has been working phenomenally well until recently when I updated the package.json, I noticed that this commit might have something to do with this. Can I suggest reversing the change please?

it's probably just because you haven't updated for a while and whatever things you were using may have changed

**Comment by DonovanDMC** [comment]
@d00mster0 you're the worst

**Pull request merged**
